services:

  odoo-db:
    image: postgres:16.2
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=odoo
      - PGPORT=${PGPORT}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

  odoo-web:
    image: odoo:17.0

    depends_on:
      - odoo-db

    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons

    environment:
      - HOST=odoo-db
      - USER=odoo
      - PASSWORD=${POSTGRES_PASSWORD}
      - PORT=${PGPORT}

volumes:
  odoo-web-data:
  odoo-db-data:
